typography_spectrum: 0.74888
color:
  brandColors:
    - '#4f87d1'
    - '#0a0c0b'
    - '#426916'
    - '#a2cd0c'
    - '#fffff1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74739
analytics:
  google: null
  facebook: null
  twitter: null
name: cch
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Cheryl Cooke Harrington
description: 'reader, writer, wonderer'
purpose: []
