name: cch
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Cheryl Cooke Harrington, Author'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4781a6'
    - '#6eacd5'
    - '#fefefe'
    - '#2c606d'
    - '#8fc4e6'
  brandStrength: 0.0397829560097307
  lightness: 0.47983050253242254
  saturation: 0.3076463653706014
  rhythmicContrast: 0.7450142365414649
purpose: []
