name: cch
favicon: null
layout_spectrum: 0.3253406516741961
typography_spectrum: 0.9178029261529446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0397829560097307
  lightness: 0.47983050253242254
  saturation: 0.3076463653706014
  rhythmicContrast: 0.7450142365414649
purpose: []
